---
- hosts: all
  tasks:
    - name: Ping Test
      shell: ping -c 5 -w 5 223.5.5.5
      delegate_to: localhost
      ignore_errors: true
      register: ping_result
    - debug: var=ping_result
