---
- hosts: 101.132.105.49
  tasks:
    - name: Ping Test
      shell: ping -c 5 -w 3 223.5.5.5  >>ping.log
      delegate_to: localhost
      ignore_errors: true
      register: ping_result
    - debug: var=ping_result
