---
- hosts: localhost
  gather_facts: F
  
  tasks:
    - name: Show df Information
      shell: df -h
      register: shell_result
    - debug:
        var: shell_result.stdout_lines
        
    - name: Show Host Name Information
      shell: localhost
      ignore_errors: true
      register: hostname_result
    - debug:
         var: hostname_result.stdout_lines

    - name: Show debug info
      debug: var=result.stdout verbosity=0
      
# - name: print facts
#      debug:
#       msg: "IPv4 address: {{ ansible_default_ipv4.address }}"

    - name: Show IP Information
      shell: ifconfig -a
      ignore_errors: true
      register: Show_IP_Result
    - debug:
         var: Show_IP_Result.stdout_lines

    - name: Ping Test
      shell: ping -c 5 -w 3 223.5.5.5  >>Ping_Result.log
      delegate_to: localhost
      ignore_errors: true
      register: ping_result
    - debug: var=ping_result.stdout verbosity=0
